#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBDS")]
	public partial class CSDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhMucBan(DanhMucBan instance);
    partial void UpdateDanhMucBan(DanhMucBan instance);
    partial void DeleteDanhMucBan(DanhMucBan instance);
    partial void InsertDanhMucChoThue(DanhMucChoThue instance);
    partial void UpdateDanhMucChoThue(DanhMucChoThue instance);
    partial void DeleteDanhMucChoThue(DanhMucChoThue instance);
    partial void InsertBangMatHang(BangMatHang instance);
    partial void UpdateBangMatHang(BangMatHang instance);
    partial void DeleteBangMatHang(BangMatHang instance);
    partial void Inserttb_dat_phong(tb_dat_phong instance);
    partial void Updatetb_dat_phong(tb_dat_phong instance);
    partial void Deletetb_dat_phong(tb_dat_phong instance);
    #endregion
		
		public CSDLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLBDSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhMucBan> DanhMucBans
		{
			get
			{
				return this.GetTable<DanhMucBan>();
			}
		}
		
		public System.Data.Linq.Table<DanhMucChoThue> DanhMucChoThues
		{
			get
			{
				return this.GetTable<DanhMucChoThue>();
			}
		}
		
		public System.Data.Linq.Table<BangMatHang> BangMatHangs
		{
			get
			{
				return this.GetTable<BangMatHang>();
			}
		}
		
		public System.Data.Linq.Table<tb_dat_phong> tb_dat_phongs
		{
			get
			{
				return this.GetTable<tb_dat_phong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucBan")]
	public partial class DanhMucBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDanhMucban;
		
		private string _TenDM;
		
		private System.Nullable<int> _ViTri;
		
		private System.Nullable<int> _HienThi;
		
		private System.Nullable<int> _IDMatHang;
		
		private EntityRef<BangMatHang> _BangMatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDanhMucbanChanging(int value);
    partial void OnIDDanhMucbanChanged();
    partial void OnTenDMChanging(string value);
    partial void OnTenDMChanged();
    partial void OnViTriChanging(System.Nullable<int> value);
    partial void OnViTriChanged();
    partial void OnHienThiChanging(System.Nullable<int> value);
    partial void OnHienThiChanged();
    partial void OnIDMatHangChanging(System.Nullable<int> value);
    partial void OnIDMatHangChanged();
    #endregion
		
		public DanhMucBan()
		{
			this._BangMatHang = default(EntityRef<BangMatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDanhMucban", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDanhMucban
		{
			get
			{
				return this._IDDanhMucban;
			}
			set
			{
				if ((this._IDDanhMucban != value))
				{
					this.OnIDDanhMucbanChanging(value);
					this.SendPropertyChanging();
					this._IDDanhMucban = value;
					this.SendPropertyChanged("IDDanhMucban");
					this.OnIDDanhMucbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDM", DbType="NVarChar(50)")]
		public string TenDM
		{
			get
			{
				return this._TenDM;
			}
			set
			{
				if ((this._TenDM != value))
				{
					this.OnTenDMChanging(value);
					this.SendPropertyChanging();
					this._TenDM = value;
					this.SendPropertyChanged("TenDM");
					this.OnTenDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="Int")]
		public System.Nullable<int> ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienThi", DbType="Int")]
		public System.Nullable<int> HienThi
		{
			get
			{
				return this._HienThi;
			}
			set
			{
				if ((this._HienThi != value))
				{
					this.OnHienThiChanging(value);
					this.SendPropertyChanging();
					this._HienThi = value;
					this.SendPropertyChanged("HienThi");
					this.OnHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMatHang", DbType="Int")]
		public System.Nullable<int> IDMatHang
		{
			get
			{
				return this._IDMatHang;
			}
			set
			{
				if ((this._IDMatHang != value))
				{
					if (this._BangMatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMatHangChanging(value);
					this.SendPropertyChanging();
					this._IDMatHang = value;
					this.SendPropertyChanged("IDMatHang");
					this.OnIDMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangMatHang_DanhMucBan", Storage="_BangMatHang", ThisKey="IDMatHang", OtherKey="IDMatHang", IsForeignKey=true)]
		public BangMatHang BangMatHang
		{
			get
			{
				return this._BangMatHang.Entity;
			}
			set
			{
				BangMatHang previousValue = this._BangMatHang.Entity;
				if (((previousValue != value) 
							|| (this._BangMatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangMatHang.Entity = null;
						previousValue.DanhMucBans.Remove(this);
					}
					this._BangMatHang.Entity = value;
					if ((value != null))
					{
						value.DanhMucBans.Add(this);
						this._IDMatHang = value.IDMatHang;
					}
					else
					{
						this._IDMatHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("BangMatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucChoThue")]
	public partial class DanhMucChoThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDanhMuc;
		
		private string _TenDM;
		
		private System.Nullable<int> _ViTri;
		
		private System.Nullable<int> _HienThi;
		
		private System.Nullable<int> _IDMatHang;
		
		private EntityRef<BangMatHang> _BangMatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDanhMucChanging(int value);
    partial void OnIDDanhMucChanged();
    partial void OnTenDMChanging(string value);
    partial void OnTenDMChanged();
    partial void OnViTriChanging(System.Nullable<int> value);
    partial void OnViTriChanged();
    partial void OnHienThiChanging(System.Nullable<int> value);
    partial void OnHienThiChanged();
    partial void OnIDMatHangChanging(System.Nullable<int> value);
    partial void OnIDMatHangChanged();
    #endregion
		
		public DanhMucChoThue()
		{
			this._BangMatHang = default(EntityRef<BangMatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDanhMuc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDanhMuc
		{
			get
			{
				return this._IDDanhMuc;
			}
			set
			{
				if ((this._IDDanhMuc != value))
				{
					this.OnIDDanhMucChanging(value);
					this.SendPropertyChanging();
					this._IDDanhMuc = value;
					this.SendPropertyChanged("IDDanhMuc");
					this.OnIDDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDM", DbType="NVarChar(50)")]
		public string TenDM
		{
			get
			{
				return this._TenDM;
			}
			set
			{
				if ((this._TenDM != value))
				{
					this.OnTenDMChanging(value);
					this.SendPropertyChanging();
					this._TenDM = value;
					this.SendPropertyChanged("TenDM");
					this.OnTenDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="Int")]
		public System.Nullable<int> ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienThi", DbType="Int")]
		public System.Nullable<int> HienThi
		{
			get
			{
				return this._HienThi;
			}
			set
			{
				if ((this._HienThi != value))
				{
					this.OnHienThiChanging(value);
					this.SendPropertyChanging();
					this._HienThi = value;
					this.SendPropertyChanged("HienThi");
					this.OnHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMatHang", DbType="Int")]
		public System.Nullable<int> IDMatHang
		{
			get
			{
				return this._IDMatHang;
			}
			set
			{
				if ((this._IDMatHang != value))
				{
					if (this._BangMatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMatHangChanging(value);
					this.SendPropertyChanging();
					this._IDMatHang = value;
					this.SendPropertyChanged("IDMatHang");
					this.OnIDMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangMatHang_DanhMucChoThue", Storage="_BangMatHang", ThisKey="IDMatHang", OtherKey="IDMatHang", IsForeignKey=true)]
		public BangMatHang BangMatHang
		{
			get
			{
				return this._BangMatHang.Entity;
			}
			set
			{
				BangMatHang previousValue = this._BangMatHang.Entity;
				if (((previousValue != value) 
							|| (this._BangMatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BangMatHang.Entity = null;
						previousValue.DanhMucChoThues.Remove(this);
					}
					this._BangMatHang.Entity = value;
					if ((value != null))
					{
						value.DanhMucChoThues.Add(this);
						this._IDMatHang = value.IDMatHang;
					}
					else
					{
						this._IDMatHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("BangMatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangMatHang")]
	public partial class BangMatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDMatHang;
		
		private string _TenMH;
		
		private string _MoTa;
		
		private string _HinhAnh;
		
		private string _Gia;
		
		private System.Nullable<int> _NoiBat;
		
		private EntitySet<DanhMucBan> _DanhMucBans;
		
		private EntitySet<DanhMucChoThue> _DanhMucChoThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMatHangChanging(int value);
    partial void OnIDMatHangChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnNoiBatChanging(System.Nullable<int> value);
    partial void OnNoiBatChanged();
    #endregion
		
		public BangMatHang()
		{
			this._DanhMucBans = new EntitySet<DanhMucBan>(new Action<DanhMucBan>(this.attach_DanhMucBans), new Action<DanhMucBan>(this.detach_DanhMucBans));
			this._DanhMucChoThues = new EntitySet<DanhMucChoThue>(new Action<DanhMucChoThue>(this.attach_DanhMucChoThues), new Action<DanhMucChoThue>(this.detach_DanhMucChoThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMatHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDMatHang
		{
			get
			{
				return this._IDMatHang;
			}
			set
			{
				if ((this._IDMatHang != value))
				{
					this.OnIDMatHangChanging(value);
					this.SendPropertyChanging();
					this._IDMatHang = value;
					this.SendPropertyChanged("IDMatHang");
					this.OnIDMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(50)")]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(MAX)")]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiBat", DbType="Int")]
		public System.Nullable<int> NoiBat
		{
			get
			{
				return this._NoiBat;
			}
			set
			{
				if ((this._NoiBat != value))
				{
					this.OnNoiBatChanging(value);
					this.SendPropertyChanging();
					this._NoiBat = value;
					this.SendPropertyChanged("NoiBat");
					this.OnNoiBatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangMatHang_DanhMucBan", Storage="_DanhMucBans", ThisKey="IDMatHang", OtherKey="IDMatHang")]
		public EntitySet<DanhMucBan> DanhMucBans
		{
			get
			{
				return this._DanhMucBans;
			}
			set
			{
				this._DanhMucBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BangMatHang_DanhMucChoThue", Storage="_DanhMucChoThues", ThisKey="IDMatHang", OtherKey="IDMatHang")]
		public EntitySet<DanhMucChoThue> DanhMucChoThues
		{
			get
			{
				return this._DanhMucChoThues;
			}
			set
			{
				this._DanhMucChoThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhMucBans(DanhMucBan entity)
		{
			this.SendPropertyChanging();
			entity.BangMatHang = this;
		}
		
		private void detach_DanhMucBans(DanhMucBan entity)
		{
			this.SendPropertyChanging();
			entity.BangMatHang = null;
		}
		
		private void attach_DanhMucChoThues(DanhMucChoThue entity)
		{
			this.SendPropertyChanging();
			entity.BangMatHang = this;
		}
		
		private void detach_DanhMucChoThues(DanhMucChoThue entity)
		{
			this.SendPropertyChanging();
			entity.BangMatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_dat_phong")]
	public partial class tb_dat_phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_don_dat_phong;
		
		private System.Nullable<int> _id_phong;
		
		private string _ten_nguoi_dat;
		
		private System.Nullable<int> _so_dien_thoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_don_dat_phongChanging(int value);
    partial void Onid_don_dat_phongChanged();
    partial void Onid_phongChanging(System.Nullable<int> value);
    partial void Onid_phongChanged();
    partial void Onten_nguoi_datChanging(string value);
    partial void Onten_nguoi_datChanged();
    partial void Onso_dien_thoaiChanging(System.Nullable<int> value);
    partial void Onso_dien_thoaiChanged();
    #endregion
		
		public tb_dat_phong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_don_dat_phong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_don_dat_phong
		{
			get
			{
				return this._id_don_dat_phong;
			}
			set
			{
				if ((this._id_don_dat_phong != value))
				{
					this.Onid_don_dat_phongChanging(value);
					this.SendPropertyChanging();
					this._id_don_dat_phong = value;
					this.SendPropertyChanged("id_don_dat_phong");
					this.Onid_don_dat_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong", DbType="Int")]
		public System.Nullable<int> id_phong
		{
			get
			{
				return this._id_phong;
			}
			set
			{
				if ((this._id_phong != value))
				{
					this.Onid_phongChanging(value);
					this.SendPropertyChanging();
					this._id_phong = value;
					this.SendPropertyChanged("id_phong");
					this.Onid_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nguoi_dat", DbType="NVarChar(50)")]
		public string ten_nguoi_dat
		{
			get
			{
				return this._ten_nguoi_dat;
			}
			set
			{
				if ((this._ten_nguoi_dat != value))
				{
					this.Onten_nguoi_datChanging(value);
					this.SendPropertyChanging();
					this._ten_nguoi_dat = value;
					this.SendPropertyChanged("ten_nguoi_dat");
					this.Onten_nguoi_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="Int")]
		public System.Nullable<int> so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
